# Generated by Django 4.0.6 on 2022-07-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdata',
            name='ax',
        ),
        migrations.RemoveField(
            model_name='tdata',
            name='ay',
        ),
        migrations.RemoveField(
            model_name='tdata',
            name='az',
        ),
        migrations.RemoveField(
            model_name='tdata',
            name='gx',
        ),
        migrations.RemoveField(
            model_name='tdata',
            name='gy',
        ),
        migrations.RemoveField(
            model_name='tdata',
            name='gz',
        ),
        migrations.AddField(
            model_name='tdata',
            name='file',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
