# Generated by Django 4.0.6 on 2022-07-28 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remove_tdata_ax_remove_tdata_ay_remove_tdata_az_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TData',
            new_name='TModels',
        ),
    ]
