# Generated by Django 4.0.6 on 2022-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_tmodels_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmodels',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/BAHILLO_RYAN.png', upload_to=''),
        ),
    ]
