# Generated by Django 4.0.6 on 2022-07-28 06:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_tmodels_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmodels',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/default.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Bahillo\\Desktop\\Untitled-thesis-proj\\website\\media'), upload_to='TrainedModels'),
        ),
    ]
