# Generated by Django 4.0.6 on 2022-07-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_tmodels_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmodels',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/default.jpg', upload_to='TrainedModels'),
        ),
    ]
