# Generated by Django 4.0.6 on 2022-08-04 09:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_alter_tmodels_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TModels',
            new_name='TrainedModel',
        ),
    ]
