# Generated by Django 4.1.3 on 2022-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='callback_file',
            field=models.FileField(default='settings.MEDIA_ROOT/default.txt', upload_to='Callbacks'),
        ),
    ]
